export const ASSIGN_PROFILE_IMAGE_DATA = 'ASSIGN_PROFILE_IMAGE_DATA'
export const CLEAR_PROFILE_IMAGE_DATA = 'CLEAR_PROFILE_IMAGE_DATA'
export const ASSIGN_PROFILE_USER_NAME = 'ASSIGN_PROFILE_USER_NAME'
export const ASSIGN_PROFILE_ADMIN = 'ASSIGN_PROFILE_ADMIN'
export const SET_PROFILE_HAS_ONBOARDED = 'SET_PROFILE_HAS_ONBOARDED'

export const BLOG_FETCH_INITIAL_LOAD = 'BLOG_FETCH_INITIAL_LOAD'
export const BLOG_FETCH_REFRESH_LOAD = 'BLOG_FETCH_REFRESH_LOAD'
export const BLOG_FETCH_HAS_ERROR = 'BLOG_FETCH_HAS_ERROR'
export const BLOG_FETCH_ERROR_MESSAGE = 'BLOG_FETCH_ERROR_MESSAGE'
export const BLOG_FETCH_SUCCESS = 'BLOG_FETCH_SUCCESS'

export const EVENT_FETCH_INITIAL_LOAD = 'EVENT_FETCH_INITIAL_LOAD'
export const EVENT_FETCH_REFRESH_LOAD = 'EVENT_FETCH_REFRESH_LOAD'
export const EVENT_FETCH_HAS_ERROR = 'EVENT_FETCH_HAS_ERROR'
export const EVENT_FETCH_ERROR_MESSAGE = 'EVENT_FETCH_ERROR_MESSAGE'
export const EVENT_FETCH_SUCCESS = 'EVENT_FETCH_SUCCESS'

export const SERMON_AUDIO_FETCH = 'SERMON_AUDIO_FETCH'
export const SERMON_AUDIO_FETCH_HAS_ERROR = 'SERMON_AUDIO_FETCH_HAS_ERROR'
export const SERMON_AUDIO_FETCH_ERROR_MESSAGE =
  'SERMON_AUDIO_FETCH_ERROR_MESSAGE'
export const SERMON_AUDIO_FETCH_SUCCESS = 'SERMON_AUDIO_FETCH_SUCCESS'

export const CACHE_IMAGE_FETCH = 'CACHE_IMAGE_FETCH'
export const CACHE_IMAGE_DOWNLOAD = 'CACHE_IMAGE_DOWNLOAD'
export const CACHE_IMAGE_SUCCESS = 'CACHE_IMAGE_SUCCESS'
export const CACHE_IMAGE_ERROR = 'CACHE_IMAGE_ERROR'
export const CACHE_IMAGE_CLEAR = 'CACHE_IMAGE_CLEAR'

export const CONNECT_CARD_SET_FORM_ATTRIBUTE = 'CONNECT_CARD_SET_FORM_ATTRIBUTE'
